### ISSUE TITLE
Analyze T2 Spheres

### ISSUE THREAD

**Issue by ellieaniosis** [imr-framework/virtual-scanner#12]
![spheres](https://user-images.githubusercontent.com/51136062/58913301-e80a4580-86e9-11e9-80dc-95bcb84a130c.JPG)
Spheres weren't accurately detected in T2.

**Comment by qianenlin** [comment]
The incorrect sphere detection originates from incorrect T2 maps. The T2 mapping model and bounds for parameters are adjusted to generate a more accurate T2 map. This fixes the sphere detection problem.
