### ISSUE TITLE
SAR Graph-TX Advanced Mode

### ISSUE THREAD

**Issue by ellieaniosis** [imr-framework/virtual-scanner#16]
The graph is showing multiple colored lines for only the whole body: 10 seconds and for the head only: 10 seconds. Only two of the colors are actually shown on the graph.
![graph](https://user-images.githubusercontent.com/51136062/61582443-d55c9c00-aaf0-11e9-9462-5302057a13ea.JPG)

**Comment by sairamgeethanath** [comment]
@ellieaniosis I was able to reproduce this on my system. This happens when you run the same file multiple times as it plots on the existing graph linked to the same .seq file. This has been fixed with commit 7f843d to master with a change on SAR_calc_main
