### ISSUE TITLE
JoSS Review: Manuscript

### ISSUE THREAD

**Issue by vsoch** [imr-framework/virtual-scanner#21]
This is the start of review for https://github.com/openjournals/joss-reviews/issues/1637.

## Manuscript

The introduction does a good job to communicate a statement of need, but I'd like to see a few more references for:

 - the opening statement about MRI being excellent and having diagnostic value (a review paper would work here)
 - a reference on simulators

It would be helpful to flush out the point about vendor neutrality - most that read aren't familiar with MRI
or that there are different companies that make the machines, software, and thus simulators.

### General Comments

 - It looks like you defined "MRI" but you didnt' specify "MR" (and use it in several spots)
 - Are you able to bold the sections in the list? I almost missed the headers when I was reading. (and the same for the subsequent lists in the paper)

Very good job on explaining your roadmap, and real life use cases. This is a cool tool I'm excited to see development for.

**Comment by vsoch** [comment]
Sorry, could you please explain how the issue has been addressed?

**Comment by tonggehua** [comment]
1. We added 4 references that discuss the diagnostic uses of MRI.
2. We added a reference on open-source simulators (in Supporting table 1 in the Pulseq-GPI paper). However, we couldn't find references to proprietary simulators. 
3. All the "MR"s have been changed to "MRI"s to avoid confusion.
4. We didn't change the styling since the main headers are already bolded in the PDF (https://github.com/openjournals/joss-papers/blob/joss.01637/joss.01637/10.21105.joss.01637.pdf). If you would prefer the first word after the bullet points to be bold, I can do that.

**Comment by vsoch** [comment]
Thank you @tonggehua ! I still have most of my review to do - I'll try to do it within the next week (a lot on my plate at the moment!)

**Comment by vsoch** [comment]
Okay, just checking over the points above now! For the bolding, I am referring to the first word (before the colon) after each section. For example, we would change:

```markdown
* Modular: ``Virtual Scanner`` consists of modules corresponding to steps in the MRI signal chain [@webb2016magnetic]. Since modern MRI systems contain multiple levels of hardware and software, it is important for researchers to select the appropriate steps for simulation when developing acquisition paradigms, analysis methods, or hardware components. Students may also choose to focus on individual aspects of the experiment.
```
to
```markdown
* **Modular**: ``Virtual Scanner`` consists of modules corresponding to steps in the MRI signal chain [@webb2016magnetic]. Since modern MRI systems contain multiple levels of hardware and software, it is important for researchers to select the appropriate steps for simulation when developing acquisition paradigms, analysis methods, or hardware components. Students may also choose to focus on individual aspects of the experiment.
```
And the difference in markdown (rendered here) is:

* Modular: ``Virtual Scanner`` consists of modules corresponding to steps in the MRI signal chain 
* **Modular**: ``Virtual Scanner`` consists of modules corresponding to steps in the MRI signal chain 

Given how it renders, I suggested this change because I missed that there was a small section heading with a colon when I first read. Does that make sense?
