### ISSUE TITLE
JoSS Review: Functionality

### ISSUE THREAD

**Issue by vsoch** [imr-framework/virtual-scanner#23]
## Functionality

This is for https://github.com/openjournals/joss-reviews/issues/1637

It's not required, but for the interested user it's sometimes helpful to give them a command to copy paste verbatim to clone the repository. The repository seems big, so a --depth 1 might help:

```bash
$ git clone --depth 1 https://github.com/imr-framework/virtual-scanner
$ cd virtual-scanner
```

There isn't any instruction to install dependencies, although I see the requirements.txt file, and it's immense. It would actually be sort of dangerous to just run this on the host (e.g., pip install -r requirements.txt) so I'd like to suggest that the others provide a Dockerfile that handles this. Anticipating that this is a Flask application, you could provide just a Dockerfile with an entrypoint to handle the database (sqlite?) and web server (if not development) or you could provide a docker-compose. Do any of the authors have experience with containers to support this?

**Comment by sairamgeethanath** [comment]
@vsoch We do not have experience with containers but find the review comment to be valuable. We will spend some time on this and get it to work as a Dockerfile

**Comment by vsoch** [comment]
okay sounds good! If you give it a solid effort and it's a stopping point for the review, then I'd be happy to help - I have a lot of experience with containers.

**Comment by vsoch** [comment]
hey @sairamgeethanath just wanted to see how you are doing here? I had forgotten about this issue, and went to continue my review, and then (again) realized I didn't want to install all the dependencies on my host (and remembered). Do you need help?

**Comment by mathieuboudreau** [comment]
@vsoch fyi I opened an issue (#25) in my own review about this too. I recommended at least adding instructions to make a virtual environment using `venv` or `conda` (if available), and the authors updated the readme to recommend using `venv`. I have another issue opened related to installation/setup in issue #29

**Comment by mathieuboudreau** [comment]
Actually I see that they removed the reference to `venv` and not just say to create a virtual environment using the tool of your choice.

**Comment by vsoch** [comment]
It's okay, I went ahead and added a basic container with instructions here - https://github.com/imr-framework/virtual-scanner/pull/35 do you want to test it out and make sure everything runs the same as it should locally? I can update the PR if there is a bug.

**Comment by sairamgeethanath** [comment]
@sravan did do a docker image and tried it yesterday which was buggy, we
will fix it on Monday.

We also have modified the readme to suit multiple install options.

Will respond in detail on Monday.

**Comment by vsoch** [comment]
@sairamgeethanath I did a pull request with a fully working Dockerfile, see #35. I've been able to continue my review in #36. #35 is good to go, if you want to merge and then work on changes for #36. Thanks!

**Comment by sairamgeethanath** [comment]
That would be great, will check it out and respond soon.
