### ISSUE TITLE
JOSS REVIEW: Clarifying how to start software

### ISSUE THREAD

**Issue by mathieuboudreau** [imr-framework/virtual-scanner#29]
This is for openjournals/joss-reviews#1637

To me, the "Getting started" instructions appear to lack a bit of clarity when it comes to using the software (both from pipy installation and from cloning the repo), as I encountered issues when following your instructions explicitly.

pypi instructions
* After installing with pipy, you're [Getting started]() instructions simply state to "run coms_server_flask.py". To people with Python experience, running a *.py file would mean to type the command `python coms_server_flask.py` in their terminal, however this fails as coms_server_flask.py is not in the path. It's not easy for users to find the correct full path of this file when it's in a virtual environment.

cloned repo instructions
* Same issue as above, except now since the user sees the code, they can dig in themselves. Still not every elegant or clear for a quick start.

I think both of these could be resolved using the [entrypoint](https://github.com/imr-framework/virtual-scanner/blob/0e805c74cd780862d617de2437eb9d54375339cd/setup.py#L27-L30) that's already implemented, but not described in the documentation. Two minor changes could solve this:

1. On [this line](https://github.com/imr-framework/virtual-scanner/blame/0e805c74cd780862d617de2437eb9d54375339cd/README.md#L21) of your README, change the command to `pip install -e .` so that the **setup.py** file is executed instead of only the requirements file, which will then create the command-line entrypoint and add it to the path.

2. On [this line](https://github.com/imr-framework/virtual-scanner/blame/0e805c74cd780862d617de2437eb9d54375339cd/README.md#L23) of the README file, change the command to simply `virtualscanner`.

**Comment by mathieuboudreau** [comment]
Actually, if you go this route, you'll need a third change, as this section of the code is only run if you call `coms_server_flask.py` as through main, and you need `os` for sure.

https://github.com/imr-framework/virtual-scanner/blob/0e805c74cd780862d617de2437eb9d54375339cd/virtualscanner/coms/coms_ui/coms_server_flask.py#L4-L10

This if statement needs to be refactored somehow so that it's applied (or at least, `os` is imported) if/when `launch_virtualscanner()` is called

**Comment by sravan953** [comment]
@mathieuboudreau I have updated the `README.md` based on your inputs. Please let us know if this works and we can go ahead and close the issue.

**Comment by sairamgeethanath** [comment]
@mathieuboudreau Can we close #29 separately now as it shows up still as open?

**Comment by tonggehua** [comment]
@mathieuboudreau Any updates on the README.md review? The latest update contains instructions for using the published Docker image as well. That makes three ways of getting started.

**Comment by mathieuboudreau** [comment]
I had booked some time this afternoon to catch up on that and other parts of your review, I'll let you know ASAP!

**Comment by mathieuboudreau** [comment]
@tonggehua FYI, if I follow the instructions under "Quick Start" and follow the typical UX path (email, subject, select sequence, then run exam), I get the following error:

<img width="1393" alt="Capture d’écran 2019-09-10 à 15 14 53" src="https://user-images.githubusercontent.com/1421029/64637241-f600ee00-d3dd-11e9-9a8a-86049caaa6e8.png">
<img width="1393" alt="Capture d’écran 2019-09-10 à 15 15 03" src="https://user-images.githubusercontent.com/1421029/64637246-f7cab180-d3dd-11e9-82da-db77e5deb1d0.png">

I'm on Mac 10.14.6 and Safari 12.1.2. Could you check to see if these instructions work for you?

**Comment by mathieuboudreau** [comment]
I just tried the "Pro start" again. A few notes:

1 - As mentionned previously, the line "Run `coms_server_flask.py` to run your changes." isn't clear enough, since the file is hidden under several folders. I recommend you change it to "Run `python virtualscanner/coms/coms_ui/coms_server_flask.p` ..." to make the life of your new users a bit easier.

2- After running it, I noticed that the user interface & functionality is different from the "Quick start" mode, so make sure to try and keep your pypi releases up to date.

3 - I can select a pulse sequence, but now "Run exam" is unclickable for me, so I can't actually run the example. Is this just a problem on my end?

**Comment by mathieuboudreau** [comment]
If it works for you and doesn't for me, I'll take a video to show you what I'm experiencing

**Comment by mathieuboudreau** [comment]
Tried the Docker instructions too, and I hit the same wall of not being able to click "Run exam""

**Comment by mathieuboudreau** [comment]
Ahh, I just tried on Chrome and it works fine - stupid Safari. Sorry about that. The only point that doesn't work for me is the first one (Quick Start).

**Comment by tonggehua** [comment]
@mathieuboudreau what version of pip-installed Virtual Scanner are you using?

**Comment by mathieuboudreau** [comment]
The latest one (1.0.22). It's dated from August 15th on pypi.

**Comment by tonggehua** [comment]
@sravan953 Maybe this is a quick fix?

**Comment by sravan953** [comment]
@mathieuboudreau Is it working now?

**Comment by mathieuboudreau** [comment]
Odd, I was sure I sent a message on Friday about this. Did I post it in the wrong issue? 

No, that fix did not resolve my issue completely. Now, when installing using `pip`, the command `virtualscanner` crashes before the server is even booted up, see error message below:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/mathieuboudreau/anaconda3/envs/vs_pypi/bin/virtualscanner", line 10, in <module>
    sys.exit(launch_virtualscanner())
  File "/Users/mathieuboudreau/anaconda3/envs/vs_pypi/lib/python3.6/site-packages/virtualscanner/coms/coms_ui/coms_server_flask.py", line 526, in launch_virtualscanner
    __modify_search_path()
  File "/Users/mathieuboudreau/anaconda3/envs/vs_pypi/lib/python3.6/site-packages/virtualscanner/coms/coms_ui/coms_server_flask.py", line 9, in __modify_search_path
    SEARCH_PATH = script_path[:script_path.index('virtual-scanner') + len('virtual-scanner') + 1]
ValueError: substring not found
```

However, if I clone the repo and install it using `pip install -e .`, it works fine. I think the reason being that you're seaching for the path `virtual-scanner` which is the **repository name**, and not the **package name** (`virtualscanner`, the folder within your repository). When installing using pypi, only the **package folder** is installed into your computer, so it won't find `virtual-scanner` in the users path.

p.s. This circular workflow (user reports bug -> dev fixes bug -> user finds another bug due to previous bug fix) shows why it might be useful to test your software using some kind of free continuous integration suite like Travis-CI (which would have flagged it during the "dev fixes bug" process in an email alert, instead of waiting until the next user encounters it). JOSS recommends it in its reviewing guidelines, but doesn't make it a requirement. Another helpful step would be to not push directly to master your changes, but create changes in branches and merge those into master using pull requests & code review/continuous integration review.

**Comment by sravan953** [comment]
@mathieuboudreau Sorry for the inconvenience, and thank you for your inputs about automated testing/CI. We are discussing and looking at ways to incorporate it in our workflow. For now, we should have fixed the startup issues whether it is a `pip install -e .`, `pip install virtual-scanner` or running in IDE. Eagerly waiting to hear back.

**Comment by mathieuboudreau** [comment]
As I said above, `pip install -e .` works for me, `pip install virtual-scanner` does not. I explain why I suspect the latter fails in my above message.

**Comment by sravan953** [comment]
Yes, it took some digging around to figure it out, but turns out the upload to PyPI was not packaging a crucial asset file along with the source code, and hence the crash. Should be fixed now!

**Comment by mathieuboudreau** [comment]
Getting close!

The server runs now with the new pypi release. I can Login, register the subject, load a sequence. However when I run the exam, it just freezes there and doesn't output the image. Here is my log (similar error as above occurs):

```
Using TensorFlow backend.
 * Serving Flask app "virtualscanner.coms.coms_ui.coms_server_flask" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Using TensorFlow backend.
 * Debugger is active!
 * Debugger PIN: 152-984-311
127.0.0.1 - - [16/Sep/2019 13:59:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:43] "GET /static/main_style.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:43] "GET /static/packages/jquery-3.3.1.min.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:43] "GET /static/log_in_style.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:43] "GET /static/virtual_scanner_logo_v1.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:43] "GET /static/log_in_func.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:43] "GET /static/logo-blue-white-onlycrown.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "POST / HTTP/1.1" 302 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/packages/Bootstrap/jquery-3.3.1.slim.min.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/packages/Bootstrap/popper.min.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/packages/Bootstrap/bootstrap.min.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/packages/Bootstrap/bootstrap.min.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/packages/jQuery-ui/jquery-ui.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/packages/jQuery-ui/jquery-ui.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/register_style.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/register_func.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/phantomAutofill.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/log_out_func.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:45] "GET /static/phantom_pics/Numerical.png HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:46] "GET /acquire HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:47] "GET /static/acquire_func.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:47] "GET /static/acquire_style.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:51] "POST /receiver HTTP/1.1" 302 -
127.0.0.1 - - [16/Sep/2019 13:59:51] "GET /register HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:53] "GET /acquire HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 13:59:59] "POST /receiver HTTP/1.1" 302 -
127.0.0.1 - - [16/Sep/2019 13:59:59] "GET /register HTTP/1.1" 200 -
{'formName': 'reg', 'subjecttype': 'Numerical', 'patid': '2321', 'name': 'Numerical', 'age': '00', 'dob': '9/16/2019', 'gender': 'other', 'weight': '3', 'weight-unit': 'kg', 'height': '20', 'height-unit': 'cm', 'inches': '', 'orient': 'HFS', 'anatomy': 'brain'}
0
127.0.0.1 - - [16/Sep/2019 14:00:01] "POST /receiver HTTP/1.1" 302 -
127.0.0.1 - - [16/Sep/2019 14:00:01] "GET /register_success HTTP/1.1" 200 -
127.0.0.1 - - [16/Sep/2019 14:00:02] "GET /acquire HTTP/1.1" 200 -
[('Numerical', 2321, 'Numerical', 0, '9/16/2019', 'other', 3.0, 20.0, 'HFS', 'brain')]
{'formName': 'acq', 'selectedSeq': 'GRE', 'TR': '200', 'TE': '10', 'FA': '90', 'sl-orient': 'axial', 'thck': '16', 'slicenum': '1', 'freq': 'x', 'ph': 'y', 'Nx': '15', 'Ny': '15', 'FOVx': '240', 'FOVy': '240'}
Traceback (most recent call last):
  File "/Users/mathieuboudreau/anaconda3/envs/vs10/lib/python3.6/site-packages/virtualscanner/server/simulation/bloch/pulseq_bloch_simulator.py", line 18, in <module>
    SEARCH_PATH = script_path[:script_path.index('virtual-scanner') + len('virtual-scanner') + 1]
ValueError: substring not found
```

**Comment by sairamgeethanath** [comment]
Path issues again  :(

**Comment by tonggehua** [comment]
@mathieuboudreau  Please try the pip install with the new 1.0.26 version. There shouldn't be a problem with seeing the simulated images now. We did find a problem with using the "virtualscanner" command on Windows (it still works on macOS) but will add the command that lets the user run coms_server_flask.py locally after a pip install.

**Comment by mathieuboudreau** [comment]
Excellent!! This installation procedure works perfectly now on my system.
