### ISSUE TITLE
JOSS REVIEW: Affiliation 1

### ISSUE THREAD

**Issue by mathieuboudreau** [imr-framework/virtual-scanner#30]
This is for openjournals/joss-reviews#1637

In your first affiliation, would you mind adding the state and country at the end to be consistent with your second affiliation?

**Comment by sairamgeethanath** [comment]
@tonggehua Can you please take a crack at all manuscript related fixes including this one? Let's schedule a Friday submission of the paper.md

**Comment by tonggehua** [comment]
Understood!

Gehua
