### ISSUE TITLE
Encountered GUI user experience bugs

### ISSUE THREAD

**Issue by mathieuboudreau** [imr-framework/virtual-scanner#34]
I encountered a few UX bugs while playing around with the GUI.

**--Bug # 1--**

Details: Re-running exam crashes UI.

How to reproduce:

* Setup in standard mode
* Register phantom
* Click acquire tab
* Select GRE sequence
* Click "Run exam"
* Wait for simulation to finish
* Without modifying anything (although it will also crash if you do), try to repeat exam by clicking "Run exam a second time".

*Note 1*: If you go through the step of reselecting a sequence after you ran your first exam, this bug doesn't happen.

*Note 2*: Same crash happens if you go straight from registering the subject to clicking run exam, without selecting a sequence, so some kind of disabling feature of the button should probably be implemented for this case.

**--Bug # 2--**

Details: Simulated figure doesn't always update if a previous one has been generated during a session

How to reproduce:

[See this video recording](https://youtu.be/u6JISfKIqhU)

Note that following these steps, it didn't always reproduce. Sometimes once I change the flip angle from from its default value of 90 to 10, the new image doesn't change in the first place at this step. From the log file, I imagine that the simulation is likely running with the correct values, maybe just the browser doesn't get update correctly? Or maybe the UI values don't update/get passed on to the backend correctly all the time?

**Comment by tonggehua** [comment]
For Bug # 1, we are aware that it happens and will disable the button if a sequence is not selected, for better user experience. 
For Bug # 2, have you tried using the left/right arrows to switch to the next image after the second one is generated? I agree that it's a good idea to always show the latest image in front. A better enhancement would be to have a work-space feature where you store past simulations and choose to view image(s) produced from each.

**Comment by mathieuboudreau** [comment]
>For Bug # 2, have you tried using the left/right arrows to switch to the next image after the second one is generated? 

Ah ha, I had missed that functionality! I just expected the newest image to show up, but it's good that I can access it using that way at least.

**Comment by Mmj94** [comment]
For Bug #2: Arrows functionality are now specified in the GUI instructions.  Instructions can be found using the "?" button in each tab.

**Comment by tonggehua** [comment]
Push for fix was not successful
