### ISSUE TITLE
grad_shapes_path_dict empty in seq2xml.py 

### ISSUE THREAD

**Issue by ANG13** [imr-framework/virtual-scanner#48]
I'm testing the function seq2xml.py with a bSSFP sequence I built in pypulseq. In this bSSFP sequence I rearrange the gradients with split_gradient_at and add_gradients in order to have the correct timings. 

However, when I try the seq2xml.py function I get this error: 

`  File "/PycharmProjects/VirtualScanner/virtualscanner/virtualscanner/server/simulation/py2jemris/seq2xml.py", line 146, in seq2xml
    g_atom.set("Filename", grad_shapes_path_dict[g_id])`

Where `grad_shapes_path_dict ` is empty. I went back to

`grad_shapes_path_dict = save_grad_library_info(seq, out_folder)`

And apparently it does not create a file because it does not pass the following if: 

`if g_ind != 0 and len(seq.grad_library.data[g_ind]) == 3 \
                and g_ind not in processed_g_inds:`

Where `len(seq.grad_library.data[g_ind]) ` is 5 in my case. Do you think you could help me with this? 

Thanks a lot!

**Comment by tonggehua** [comment]
@ANG13 Thank you for the valuable feedback. Is it possible for you to share the bSSFP script so that I can debug it?

**Comment by ZemaTimoteo** [comment]
Hi @ANG13 & @tonggehua . 

I am facing a similar issue. I am trying to use seq2xml.py to convert a Multi Spin Echo (MSE) sequence i just created. However, i encounter the same problem when facing the if clause. 

My MSE is based on a Turbo Spin-Echo (TSE) sequence from the pypulseq example sequences folder. 

How can I handle this issue?
I tried to remove the <len(seq.grad_library.data[g_ind]) == 3>  if clause but I encountered further issues .

Thank you for your help!

**Comment by tonggehua** [comment]
@ANG13 @ZemaTimoteo  
Which version of Pulseq did you use? Was the sequence built with Pypulseq or the original MATLAB Pulseq?

In the version I worked on,  `seq.grad_library.data` had 3 entries (amplitude, shape id, and delay) for the [GRADIENTS] type (not trapezoid, but arbitrary gradients, which anything created with `make_extended_trapezoid` results in). It seems that the version you use has 5 entries. I'd like to make it work using a version check. 

In addition, please send me your `.seq` files to ensure the code works.  Thanks!

**Comment by ANG13** [comment]
Hi @tonggehua, I used pypulseq 1.2.0 to build the bSSFP sequence ( *.seq here: [bSSFP_pypulseq.zip](https://github.com/imr-framework/virtual-scanner/files/6057846/bSSFP_pypulseq.zip)). 

I also have arbitrary gradients in the z direction, so I had to change the file  `save_grad_library_info.py ` to account also for arbitrary gradients in that direction. But I'm not sure I did the correct changes because I still have some mismatch between *.seq and *.xml.

Thanks a lot!

**Comment by ZemaTimoteo** [comment]
I tried to change the value in the if clause from 3 to 5 but i know get this error:

` File "D:/Tiago/Trabalho/2021_2025_PhD/Projects/Toolboxes/Python/py2jemris\seq2xml.py", line 264, in save_grad_library_info
    t_points = this_block.gx.t
AttributeError: 'types.SimpleNamespace' object has no attribute 'gx' `


I share a Google drive link in which you can find my '.seq' MSE file
https://drive.google.com/file/d/1g2SP_146Z88JyZFKCJfy4uLYidNRo1K3/view?usp=sharing

**Comment by tonggehua** [comment]
> Hi @tonggehua, I used pypulseq 1.2.0 to build the bSSFP sequence ( *.seq here: [bSSFP_pypulseq.zip](https://github.com/imr-framework/virtual-scanner/files/6057846/bSSFP_pypulseq.zip)).
> 
> I also have arbitrary gradients in the z direction, so I had to change the file `save_grad_library_info.py ` to account also for arbitrary gradients in that direction. But I'm not sure I did the correct changes because I still have some mismatch between *.seq and *.xml.
> 
> Thanks a lot!

@ANG13 On the header of this file, it says "Created by JEMRIS 2.8.3". Is this the correct file? Right now, Pypulseq is not back-compatible to this version and I cannot read the file.

**Comment by tonggehua** [comment]
@ZemaTimoteo @ANG13 Please visit the [new py2jemris repository](https://github.com/imr-framework/py2jemris) to try the up-to-date version of `seq2xml`. I tried loading the MSE file provided by @ZemaTimoteo and it ran without generating any errors. From now on, all new development will be on this new repository and the outdated code will be removed from the Virtual Scanner project soon.

**Comment by tonggehua** [comment]
I am closing this thread. If there are issues after retest using the new code, **please post an issue at the new repository.** Thanks so much for your feedback and hope you continue to try out this package!
